### ISSUE TITLE
Deploying to Cloudflare Pages

### ISSUE THREAD

**Issue by richard-herbert-fullpoint** [rothsandro/eleventy-notes#8]
Loving the project!

Has anyone deployed to Cloudflare Pages?

I'm having this issue...

```
2023-02-18T17:05:56.592307Z	Cloning repository...
2023-02-18T17:05:57.723905Z	From https://github.com/xxxxxxxxxxxxxxxx
2023-02-18T17:05:57.724603Z	 * branch            d2c3fbe1a432bd6de1b3044c9805a581da6f0b18 -> FETCH_HEAD
2023-02-18T17:05:57.724803Z	
2023-02-18T17:05:57.795374Z	HEAD is now at d2c3fbe Updated Notes to v0.4.0 and 11ty to v2
2023-02-18T17:05:57.795966Z	
2023-02-18T17:05:57.95071Z	
2023-02-18T17:05:57.980459Z	Success: Finished cloning repository files
2023-02-18T17:05:58.641333Z	Installing dependencies
2023-02-18T17:05:58.654388Z	Python version set to 2.7
2023-02-18T17:06:02.258282Z	Downloading and installing node v14.21.3...
2023-02-18T17:06:02.718814Z	Downloading https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz...
2023-02-18T17:06:03.168864Z	Computing checksum with sha256sum
2023-02-18T17:06:03.298467Z	Checksums matched!
2023-02-18T17:06:07.964813Z	Now using node v14.21.3 (npm v6.14.18)
2023-02-18T17:06:08.378593Z	Started restoring cached build plugins
2023-02-18T17:06:08.392797Z	Finished restoring cached build plugins
2023-02-18T17:06:08.930423Z	Attempting ruby version 2.7.1, read from environment
2023-02-18T17:06:12.951835Z	Using ruby version 2.7.1
2023-02-18T17:06:13.327552Z	Using PHP version 5.6
2023-02-18T17:06:13.502289Z	5.2 is already installed.
2023-02-18T17:06:13.534817Z	Using Swift version 5.2
2023-02-18T17:06:13.535302Z	Started restoring cached node modules
2023-02-18T17:06:13.553017Z	Finished restoring cached node modules
2023-02-18T17:06:13.825213Z	Installing NPM modules using NPM version 6.14.18
2023-02-18T17:06:14.841363Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2023-02-18T17:06:28.915847Z	
2023-02-18T17:06:28.916287Z	> @parcel/watcher@2.0.7 install /opt/buildhome/repo/node_modules/@parcel/watcher
2023-02-18T17:06:28.916466Z	> node-gyp-build
2023-02-18T17:06:28.916585Z	
2023-02-18T17:06:29.137359Z	
2023-02-18T17:06:29.137831Z	> msgpackr-extract@2.2.0 install /opt/buildhome/repo/node_modules/msgpackr-extract
2023-02-18T17:06:29.138091Z	> node-gyp-build-optional-packages
2023-02-18T17:06:29.138328Z	
2023-02-18T17:06:29.364296Z	
2023-02-18T17:06:29.364686Z	> lmdb@2.5.2 install /opt/buildhome/repo/node_modules/lmdb
2023-02-18T17:06:29.364939Z	> node-gyp-build-optional-packages
2023-02-18T17:06:29.365092Z	
2023-02-18T17:06:29.64133Z	
2023-02-18T17:06:29.641713Z	> core-js@3.27.2 postinstall /opt/buildhome/repo/node_modules/core-js
2023-02-18T17:06:29.643194Z	> node -e "try{require('./postinstall')}catch(e){}"
2023-02-18T17:06:29.643407Z	
2023-02-18T17:06:29.750431Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2023-02-18T17:06:29.750747Z	
2023-02-18T17:06:29.750902Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2023-02-18T17:06:29.751033Z	[96m>[94m https://opencollective.com/core-js [0m
2023-02-18T17:06:29.751161Z	[96m>[94m https://patreon.com/zloirock [0m
2023-02-18T17:06:29.751286Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2023-02-18T17:06:29.751397Z	
2023-02-18T17:06:29.751511Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2023-02-18T17:06:29.751625Z	
2023-02-18T17:06:30.15371Z	npm WARN eleventy-notes@0.4.0 No description
2023-02-18T17:06:30.159799Z	npm WARN eleventy-notes@0.4.0 No repository field.
2023-02-18T17:06:30.168718Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @lmdb/lmdb-linux-arm@2.5.2 (node_modules/@lmdb/lmdb-linux-arm):
2023-02-18T17:06:30.168981Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @lmdb/lmdb-linux-arm@2.5.2: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.178939Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @lmdb/lmdb-darwin-x64@2.5.2 (node_modules/@lmdb/lmdb-darwin-x64):
2023-02-18T17:06:30.179212Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @lmdb/lmdb-darwin-x64@2.5.2: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.186626Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @lmdb/lmdb-darwin-arm64@2.5.2 (node_modules/@lmdb/lmdb-darwin-arm64):
2023-02-18T17:06:30.18686Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @lmdb/lmdb-darwin-arm64@2.5.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.194429Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @lmdb/lmdb-linux-arm64@2.5.2 (node_modules/@lmdb/lmdb-linux-arm64):
2023-02-18T17:06:30.194663Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @lmdb/lmdb-linux-arm64@2.5.2: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.202957Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @msgpackr-extract/msgpackr-extract-darwin-x64@2.2.0 (node_modules/@msgpackr-extract/msgpackr-extract-darwin-x64):
2023-02-18T17:06:30.203226Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @msgpackr-extract/msgpackr-extract-darwin-x64@2.2.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.211379Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @msgpackr-extract/msgpackr-extract-linux-arm64@2.2.0 (node_modules/@msgpackr-extract/msgpackr-extract-linux-arm64):
2023-02-18T17:06:30.211589Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @msgpackr-extract/msgpackr-extract-linux-arm64@2.2.0: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.219027Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @lmdb/lmdb-win32-x64@2.5.2 (node_modules/@lmdb/lmdb-win32-x64):
2023-02-18T17:06:30.219291Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @lmdb/lmdb-win32-x64@2.5.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.226636Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @msgpackr-extract/msgpackr-extract-linux-arm@2.2.0 (node_modules/@msgpackr-extract/msgpackr-extract-linux-arm):
2023-02-18T17:06:30.226886Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @msgpackr-extract/msgpackr-extract-linux-arm@2.2.0: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.234169Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @msgpackr-extract/msgpackr-extract-win32-x64@2.2.0 (node_modules/@msgpackr-extract/msgpackr-extract-win32-x64):
2023-02-18T17:06:30.234386Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @msgpackr-extract/msgpackr-extract-win32-x64@2.2.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.24171Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @msgpackr-extract/msgpackr-extract-darwin-arm64@2.2.0 (node_modules/@msgpackr-extract/msgpackr-extract-darwin-arm64):
2023-02-18T17:06:30.241906Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @msgpackr-extract/msgpackr-extract-darwin-arm64@2.2.0: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.250578Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-win32-x64-msvc@1.17.1 (node_modules/lightningcss-win32-x64-msvc):
2023-02-18T17:06:30.250786Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-win32-x64-msvc@1.17.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.258669Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-linux-arm64-musl@1.17.1 (node_modules/lightningcss-linux-arm64-musl):
2023-02-18T17:06:30.258862Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-linux-arm64-musl@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.266387Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-darwin-x64@1.17.1 (node_modules/lightningcss-darwin-x64):
2023-02-18T17:06:30.266591Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-darwin-x64@1.17.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.274101Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-linux-arm-gnueabihf@1.17.1 (node_modules/lightningcss-linux-arm-gnueabihf):
2023-02-18T17:06:30.274342Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-linux-arm-gnueabihf@1.17.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.282024Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-darwin-arm64@1.17.1 (node_modules/lightningcss-darwin-arm64):
2023-02-18T17:06:30.28225Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-darwin-arm64@1.17.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.290732Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-linux-arm64-gnu@1.17.1 (node_modules/lightningcss-linux-arm64-gnu):
2023-02-18T17:06:30.29094Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-linux-arm64-gnu@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.301289Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2023-02-18T17:06:30.301513Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2023-02-18T17:06:30.301952Z	
2023-02-18T17:06:30.304363Z	added 537 packages from 410 contributors and audited 555 packages in 15.505s
2023-02-18T17:06:30.475598Z	
2023-02-18T17:06:30.475983Z	147 packages are looking for funding
2023-02-18T17:06:30.476183Z	  run `npm fund` for details
2023-02-18T17:06:30.476359Z	
2023-02-18T17:06:30.476519Z	found 0 vulnerabilities
2023-02-18T17:06:30.476652Z	
2023-02-18T17:06:30.497575Z	NPM modules installed
2023-02-18T17:06:30.902003Z	Installing Hugo 0.54.0
2023-02-18T17:06:31.593571Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2023-02-18T17:06:31.59768Z	Started restoring cached go cache
2023-02-18T17:06:31.618233Z	Finished restoring cached go cache
2023-02-18T17:06:31.769656Z	go version go1.14.4 linux/amd64
2023-02-18T17:06:31.784374Z	go version go1.14.4 linux/amd64
2023-02-18T17:06:31.787622Z	Installing missing commands
2023-02-18T17:06:31.787875Z	Verify run directory
2023-02-18T17:06:31.78804Z	Executing user command: npm run build
2023-02-18T17:06:32.150705Z	
2023-02-18T17:06:32.151063Z	> eleventy-notes@0.4.0 build /opt/buildhome/repo
2023-02-18T17:06:32.151279Z	> cross-env ELEVENTY_ENV=production npm-run-all clean 11ty:build
2023-02-18T17:06:32.151437Z	
2023-02-18T17:06:32.799951Z	
2023-02-18T17:06:32.80038Z	> eleventy-notes@0.4.0 clean /opt/buildhome/repo
2023-02-18T17:06:32.800597Z	> rimraf dist
2023-02-18T17:06:32.800797Z	
2023-02-18T17:06:33.23556Z	
2023-02-18T17:06:33.235888Z	> eleventy-notes@0.4.0 11ty:build /opt/buildhome/repo
2023-02-18T17:06:33.236042Z	> npm run clean && eleventy
2023-02-18T17:06:33.236193Z	
2023-02-18T17:06:33.558093Z	
2023-02-18T17:06:33.558466Z	> eleventy-notes@0.4.0 clean /opt/buildhome/repo
2023-02-18T17:06:33.558635Z	> rimraf dist
2023-02-18T17:06:33.558788Z	
2023-02-18T17:06:34.40508Z	[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
2023-02-18T17:06:34.406477Z	[11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
2023-02-18T17:06:34.406774Z	[11ty] 2. Unexpected token '??=' (via SyntaxError)
2023-02-18T17:06:34.406926Z	[11ty] 
2023-02-18T17:06:34.407072Z	[11ty] Original error stack trace: /opt/buildhome/repo/_config/collections/groupedNotes.collection.js:11
2023-02-18T17:06:34.407215Z	[11ty]     groups[folder] ??= [];
2023-02-18T17:06:34.407348Z	[11ty]                    ^^^
2023-02-18T17:06:34.407488Z	[11ty] 
2023-02-18T17:06:34.407607Z	[11ty] SyntaxError: Unexpected token '??='
2023-02-18T17:06:34.407716Z	[11ty]     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
2023-02-18T17:06:34.407823Z	[11ty]     at Module._compile (internal/modules/cjs/loader.js:1078:27)
2023-02-18T17:06:34.407927Z	[11ty]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
2023-02-18T17:06:34.408052Z	[11ty]     at Module.load (internal/modules/cjs/loader.js:979:32)
2023-02-18T17:06:34.408193Z	[11ty]     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
2023-02-18T17:06:34.408303Z	[11ty]     at Module.require (internal/modules/cjs/loader.js:1003:19)
2023-02-18T17:06:34.408418Z	[11ty]     at require (internal/modules/cjs/helpers.js:107:18)
2023-02-18T17:06:34.408527Z	[11ty]     at /opt/buildhome/repo/_config/utils/loader.util.js:48:20
2023-02-18T17:06:34.408646Z	[11ty]     at Array.forEach (<anonymous>)
2023-02-18T17:06:34.408756Z	[11ty]     at load (/opt/buildhome/repo/_config/utils/loader.util.js:43:16)
2023-02-18T17:06:34.421074Z	npm ERR! code ELIFECYCLE
2023-02-18T17:06:34.421463Z	npm ERR! errno 1
2023-02-18T17:06:34.424842Z	npm ERR! eleventy-notes@0.4.0 11ty:build: `npm run clean && eleventy`
2023-02-18T17:06:34.425074Z	npm ERR! Exit status 1
2023-02-18T17:06:34.425403Z	npm ERR! 
2023-02-18T17:06:34.425693Z	npm ERR! Failed at the eleventy-notes@0.4.0 11ty:build script.
2023-02-18T17:06:34.42585Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2023-02-18T17:06:34.459149Z	
2023-02-18T17:06:34.459431Z	npm ERR! A complete log of this run can be found in:
2023-02-18T17:06:34.459582Z	npm ERR!     /opt/buildhome/.npm/_logs/2023-02-18T17_06_34_425Z-debug.log
2023-02-18T17:06:34.466557Z	ERROR: "11ty:build" exited with 1.
2023-02-18T17:06:34.481459Z	npm ERR! code ELIFECYCLE
2023-02-18T17:06:34.481822Z	npm ERR! errno 1
2023-02-18T17:06:34.485264Z	npm ERR! eleventy-notes@0.4.0 build: `cross-env ELEVENTY_ENV=production npm-run-all clean 11ty:build`
2023-02-18T17:06:34.485496Z	npm ERR! Exit status 1
2023-02-18T17:06:34.485832Z	npm ERR! 
2023-02-18T17:06:34.486108Z	npm ERR! Failed at the eleventy-notes@0.4.0 build script.
2023-02-18T17:06:34.48638Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2023-02-18T17:06:34.493815Z	
2023-02-18T17:06:34.494021Z	npm ERR! A complete log of this run can be found in:
2023-02-18T17:06:34.494176Z	npm ERR!     /opt/buildhome/.npm/_logs/2023-02-18T17_06_34_486Z-debug.log
2023-02-18T17:06:34.503592Z	Failed: build command exited with code: 1
2023-02-18T17:06:36.532582Z	Failed: an internal error occurred
```

**Comment by rothsandro** [comment]
> Now using node v14.21.3 (npm v6.14.18)

Eleventy Notes requires Node 16 or higher. Can you try it again with Node 16?
I've never used Cloudflare Pages but its hould be possible via `NODE_VERSION` environment variable: https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools

**Comment by rothsandro** [comment]
I can reproduce the error. It looks like Cloudflare does some kind of Git sparse-checkout (or limiting the directory access in another way) when configuring the root directory, which makes all notes and the layout path `../.app/_includes` inaccessible to Eleventy.

For now you can fix the build using the following settings:

| Property                | Value                                                      |
|-------------------------|------------------------------------------------------------|
| Build command           | `npm install --prefix .app && npm run build --prefix .app` |
| Build output directory  |`.app/dist/`                                                |
| Root Directory          | `/` (default)                                              |

I will keep this issue open and investigate the problem further to see if there is a better solution (and probably add the build settings to the documentation).

**Comment by rothsandro** [comment]
Looks like the commands mentioned above are the way to go, I couldn't find a better solution.
I will add them to the docs but have to fix the "Edit this note" link first, which doesn't work on Cloudflare.
